#!/bin/bash
#
#	MultiBeast script for setting audio device id 3 in Clover config.plist
#
#	Usage:
#
#		OptionalNative3PortAudio "Explicit path for config.plist"
#
#	Return Codes:
#
#		0 - Successfully set audio device id 3 in Clover config.plist
#		1 - Failed to set audio device id 3 in Clover config.plist
#
# 	Copyright (C) tonymacx86 LLC

CONFIG_PLIST=${1}

if /usr/libexec/PlistBuddy -c "Set Devices:Audio:Inject 3" ${CONFIG_PLIST} ; then
	exit 0
else
	exit 1
fi